export const skillKeywords = [
  // Languages
  "javascript",
  "typescript",
  "python",
  "java",
  "c++",
  "c#",
  "go",
  "rust",
  "swift",
  "kotlin",
  "php",
  "ruby",
  "scala",
  "r",
  "matlab",
  "c",
  // Frontend
  "react",
  "angular",
  "vue",
  "svelte",
  "jquery",
  "redux",
  "zustand",
  "next.js",
  "nuxt.js",
  "gatsby",
  "html",
  "css",
  "sass",
  "less",
  "tailwind",
  "bootstrap",
  "material-ui",
  "webpack",
  "babel",
  // Backend
  "node.js",
  "express.js",
  "django",
  "flask",
  "spring",
  "spring boot",
  "laravel",
  ".net",
  "asp.net",
  "ruby on rails",
  "nestjs",
  "fastapi",
  "graphql",
  "rest",
  "api",
  // Databases
  "sql",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "elasticsearch",
  "cassandra",
  "dynamodb",
  "sqlite",
  "oracle",
  "bigquery",
  // Cloud & DevOps
  "aws",
  "azure",
  "gcp",
  "docker",
  "kubernetes",
  "jenkins",
  "gitlab ci",
  "github actions",
  "terraform",
  "ansible",
  "ci/cd",
  "devops",
  "serverless",
  // Mobile
  "react native",
  "flutter",
  "swift",
  "kotlin",
  "android",
  "ios",
  // Data Science & Machine Learning
  "r",
  "pandas",
  "numpy",
  "scikit-learn",
  "tensorflow",
  "pytorch",
  "hadoop",
  "spark",
  "jupyter",
  "sql",
  // Other Tools & Methodologies
  "git",
  "github",
  "gitlab",
  "jira",
  "confluence",
  "agile",
  "scrum",
  "kanban",
  "tdd",
  "bdd",
  "oop",
  "dsa",
  "linux",
  "bash",
  "shell",
  "figma",
  "photoshop",
  "illustrator",
  "aws s3",
  "aws lambda",
];

export const educationKeywords = [
  "bachelor",
  "master",
  "phd",
  "university",
  "college",
  "institute",
];

export const EMAIL_REGEX =
  /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g;
export const PHONE_REGEX =
  /(?:\+?91[-.\s]?)?(?:\+?1[-.\s]?)?(?:\+?44[-.\s]?)?(?:\(?[0-9]{2,4}\)?[-.\s]?)?[0-9]{3,4}[-.\s]?[0-9]{3,4}[-.\s]?[0-9]{0,4}/g;
export const YEAR_RANGE_REGEX = /(\b\d{4}\s*-\s*(?:Present|present|\d{4})\b)/g;
